const { GoogleGenerativeAI } = require("@google/generative-ai");

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

exports.detectAIText = async (req, res) => {
    const { text } = req.body;
    if (!text) return res.status(400).json({ error: "Text is required" });

    try {
        const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

        const prompt = `
You are an AI detector. I will give you a piece of text. 
Estimate how much of it is likely generated by an AI like ChatGPT, Gemini, etc.
Just return a number between 0 to 100. No explanation.

Text:
"""${text}"""
`;

        const result = await model.generateContent(prompt);
        const response = await result.response.text();

        const percentage = parseInt(response.match(/\d+/)?.[0] || "0", 10);

        res.json({
            textPreview: text.slice(0, 100) + "...",
            aiLikelihoodPercent: percentage
        });
    } catch (err) {
        console.error(err);
        res.status(500).json({ error: "Gemini API call failed "+err });
    }
};
 